me: basil
server_type: :test
plugins_directory: ./plugins

jenkins:
  host:     x
  port:     0
  user:     x
  password: x

jira:
  host:     x
  port:     0
  user:     x
  password: x

airbrake:
  account: x
  project: 0
  token:   x

email:
  server:   x
  port:     0
  username: x
  password: x
  inbox:    x

twitter:
  consumer_key:       x
  consumer_secret:    x
  oauth_token:        x
  oauth_token_secret: x
